ADD : teachers backend with integration
Artsy-Technologies/ERP-System pull request #33
Opened 2024-10-06 07:33 UTC by RaiDevX8

2024-10-07 11:02 UTC, Prithwi32 requested changes

2024-10-07 11:02 UTC, Prithwi32 commented on client/.env.sample
why necessary of / in url?

2024-10-07 11:02 UTC, Prithwi32 commented on client/src/App.js
use base url variable defined in .evn file

2024-10-07 12:48 UTC, RaiDevX8 commented on client/src/App.js
Ok

2024-10-09 16:51 UTC, RaiDevX8 commented on client/.env.sample
done

2024-10-09 18:16 UTC, merged

2024-10-09 18:34 UTC, RaiDevX8 reviewed
sent another pr

2024-10-09 18:37 UTC, Prithwi32 commented
> sent another pr

It's fine..i changed and merged